# Go Report Card A+ Configuration
# Only enable linters that are actually checked by goreportcard.com

version: 2

linters:
  enable:
    - errcheck      # unchecked errors (goreportcard checks this)
    - gocyclo      # cyclomatic complexity (goreportcard checks this)
    - govet        # go vet (goreportcard checks this)
    - ineffassign  # ineffectual assignments (goreportcard checks this)
    - misspell     # misspellings (goreportcard checks this)

  disable-all: true

linters-settings:
  gocyclo:
    min-complexity: 15  # same as goreportcard
  misspell:
    locale: US

issues:
  exclude-rules:
    # Allow some flexibility in tests
    - path: _test\.go
      linters: [errcheck, gocyclo]
    # Allow complexity in main CLI files
    - path: main\.go
      linters: [gocyclo]

run:
  timeout: 5m