project_name: qnap-vm

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: qnap-vm
    binary: qnap-vm
    main: .
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: qnap-vm
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: scttfrdmn
    name: qnap-vm
  name_template: "v{{ .Version }}"
  draft: false
  prerelease: auto

brews:
  - name: qnap-vm
    repository:
      owner: scttfrdmn
      name: homebrew-qnap-vm
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/scttfrdmn/qnap-vm
    description: "A command-line tool for managing virtual machines on QNAP devices with Virtualization Station"
    license: MIT
    skip_upload: auto
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    install: |
      bin.install "qnap-vm"
    test: |
      system "#{bin}/qnap-vm version"

dockers:
  - image_templates:
      - "ghcr.io/scttfrdmn/qnap-vm:{{ .Version }}-amd64"
      - "ghcr.io/scttfrdmn/qnap-vm:latest-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - image_templates:
      - "ghcr.io/scttfrdmn/qnap-vm:{{ .Version }}-arm64"
      - "ghcr.io/scttfrdmn/qnap-vm:latest-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/scttfrdmn/qnap-vm:{{ .Version }}"
    image_templates:
      - "ghcr.io/scttfrdmn/qnap-vm:{{ .Version }}-amd64"
      - "ghcr.io/scttfrdmn/qnap-vm:{{ .Version }}-arm64"
  - name_template: "ghcr.io/scttfrdmn/qnap-vm:latest"
    image_templates:
      - "ghcr.io/scttfrdmn/qnap-vm:latest-amd64"
      - "ghcr.io/scttfrdmn/qnap-vm:latest-arm64"